# Generated by Django 4.1.2 on 2022-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attribute_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=120, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='значение'),
        ),
    ]
