# Generated by Django 4.1.2 on 2022-10-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_2_price_alter_productimage_2_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_2',
            options={'verbose_name': 'Категория Солнечные панели', 'verbose_name_plural': 'Категория Солнечные панели'},
        ),
        migrations.AlterModelOptions(
            name='product_2',
            options={'verbose_name': 'Солнечные панели', 'verbose_name_plural': 'Солнечные панели'},
        ),
        migrations.AlterModelOptions(
            name='productimage_2',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображение продукта'},
        ),
        migrations.AddField(
            model_name='attribute_2',
            name='key_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ключ'),
        ),
        migrations.AddField(
            model_name='attribute_2',
            name='key_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='ключ'),
        ),
        migrations.AddField(
            model_name='attribute_2',
            name='value_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='attribute_2',
            name='value_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='category_2',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='category_2',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='product_2',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product_2',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product_2',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='product_2',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='key',
            field=models.CharField(max_length=100, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_2', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='value',
            field=models.CharField(max_length=120, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='category_2',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='марка'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category_2', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='name',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product_2',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='productimage_2',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='изображение'),
        ),
    ]
