# Generated by Django 4.1.2 on 2022-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_2_options_alter_product_2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute_2',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='value',
            field=models.CharField(max_length=120, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='value_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='attribute_2',
            name='value_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='значение'),
        ),
    ]
